"""Add queue field to ray_jobs

Revision ID: 7d43d0dab2e1
Revises: 74725c3080f4
Create Date: 2025-09-10 02:08:49.580249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d43d0dab2e1'
down_revision = '74725c3080f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 queue 字段到 ray_jobs 表
    op.add_column('ray_jobs', sa.Column('queue', sa.String(), nullable=False, server_default='default'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ray_jobs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('github_repo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('branch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('entry_point', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('template_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notebook_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ray_job_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dashboard_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('config', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_config', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ray_jobs_pkey')
    )
    op.create_index('ix_ray_jobs_job_id', 'ray_jobs', ['job_id'], unique=False)
    op.create_index('ix_ray_jobs_id', 'ray_jobs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###