apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: webapp-starter
data:
  POSTGRES_SERVER: postgres-service
  POSTGRES_PORT: "5432"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: webapp-starter
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: db-migration
        image: webapp-starter/backend:latest
        command: ['sh', '-c', 'alembic upgrade head && python app/db/init_db.py']
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: postgres-secret
      containers:
      - name: backend
        image: webapp-starter/backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: postgres-secret
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: webapp-starter
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP